### ISSUE TITLE
Parameter sweep crashes, as - I guess - the graphics card is not recognized anymore

### ISSUE THREAD

**Issue by vapi0405** [HenriquesLab/NanoJ-eSRRF#6]
Hi there,

I often receive the following error message during the parameter sweep. The Graphics card is an Nvidia Quadro RTX4000.

(Fiji Is Just) ImageJ 2.3.0/1.53q; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 1711MB of 48781MB (3%)

com.jogamp.opencl.CLException$CLDeviceNotAvailableException: can not create CL context [error: CL_DEVICE_NOT_AVAILABLE]
at com.jogamp.opencl.CLException.checkForError(CLException.java:73)
at com.jogamp.opencl.CLContext.createContextFromType(CLContext.java:206)
at com.jogamp.opencl.CLContext.create(CLContext.java:174)
at com.jogamp.opencl.CLContext.create(CLContext.java:157)
at nanoj.liveSRRF.LiveSRRF_CL.initialise(LiveSRRF_CL.java:179)
at nanoj.liveSRRF.gui.ParametersSweep_.run(ParametersSweep_.java:410)
at ij.IJ.runUserPlugIn(IJ.java:243)
at ij.IJ.runPlugIn(IJ.java:204)
at ij.Executer.runCommand(Executer.java:152)
at ij.Executer.run(Executer.java:70)
at java.lang.Thread.run(Thread.java:748)

eSRRF won't work after this error until a restart of FIJI.

Any clues?

Thank you!

Best regards,
Valentin

**Comment by HannahSHeil** [comment]
Hi Valentine, 

Thanks for reporting this! I'll take a look. 
Best, Hannah

**Comment by vapi0405** [comment]
Hi Hannah,

thank you very much! 

Best regards,
Valentin

**Comment by DSbiomedAU** [comment]
I was also experiencing this issue with the NOJRE version of FIJI under windows 10 with an Nvidia 2070S. 
However, it works on a freshly (19/Aug/22) updated FIJI with bundled JRE, since I have not updated my system JRE in a while maybe that may be a potential problem source. Thanks for the release!

**Comment by bheit** [comment]
I am getting a similar error on a 3060 graphics card. At first I thought the computer may be putting the graphics card to sleep, but adjusting the power settings so the screen remains on at all times did not change the behaviour. In my case, the sweep always crashes on iteration 30 or 31 of 60. Error message is as follows:

```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 3810MB of 12059MB (31%)
 
com.jogamp.opencl.CLException$CLInvalidCommandQueueException: can not finish command queue [error: CL_INVALID_COMMAND_QUEUE]
	at com.jogamp.opencl.CLException.checkForError(CLException.java:67)
	at com.jogamp.opencl.CLCommandQueue.finish(CLCommandQueue.java:1790)
	at nanoj.liveSRRF.LiveSRRF_CL.calculateSRRF(LiveSRRF_CL.java:739)
	at nanoj.liveSRRF.gui.ParametersSweep_.calculateLiveSRRFframeLoad(ParametersSweep_.java:821)
	at nanoj.liveSRRF.gui.ParametersSweep_.run(ParametersSweep_.java:456)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by vapi0405** [comment]
Thanks for all the tips, yet a fresh install didn't do the job in my case.

**Comment by zcl20** [comment]
I have experimented the similar problem. It worked on when i set the device to defaut rather than the specific gpu.
